name: UI Tests

on:
  workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UI tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          VALID_USERNAME: ${{ secrets.VALID_USERNAME }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
        run: |
          pytest -s -v tests/test_login_page.py --alluredir=allure_results
        continue-on-error: true

      - name: Generate Allure report with history
        if: always()
        id: allure_report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: ./allure_results
          gh_pages: ./.github/gh-pages
          allure_report: ./allure-report
          allure_history: ./allure-report/history
          keep_reports: 10

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/demo'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true