name: UI Tests

on:
  workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.30.0/allure_2.30.0-1_all.deb
          sudo dpkg -i allure_2.30.0-1_all.deb
          rm allure_2.30.0-1_all.deb

      - name: Run UI tests
        run: |
          pytest -s -v tests/test_login_page.py --alluredir=allure-results
        continue-on-error: true

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy Allure results to gh-pages
        if: always()
        run: |
          mkdir -p gh-pages/allure-results
          cp -r allure-results/* gh-pages/allure-results/

      - name: Generate Allure report in gh-pages
        if: always()
        run: |
          cd gh-pages
          allure generate allure-results -o allure-history --clean
        continue-on-error: true

      - name: Commit changes to gh-pages
        if: always()
        run: |
          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add allure-history
          git commit -m "Update Allure report" || echo "No changes to commit"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Deploy to GitHub Pages
        if: always()
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.CI_TOKEN }}